services:

  # Backend
  backend:
    image: transcriber-backend
    build: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.prod
    depends_on:
      - postgres
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/storage/
      - whisper_models:/root/.cache/huggingface/

  # Celery worker
  celery:
    image: transcriber-backend
    command: celery -A config worker -B -l INFO
    env_file:
      - ./backend/.env.prod
    depends_on:
      - backend
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/storage/
      - whisper_models:/root/.cache/huggingface/

  # Migration
  migration:
    image: transcriber-backend
    env_file:
        - ./backend/.env.prod
    command: python manage.py migrate
    depends_on:
        - postgres

  # Collectstatic
  collectstatic:
    image: transcriber-backend
    env_file:
        - ./backend/.env.prod
    command: python manage.py collectstatic --noinput
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/storage/

  # Frontend Nginx
  backend-nginx:
    image: nginx:1.25-alpine
    ports:
      - "9000:9000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static/:ro
      - media_volume:/app/storage/:ro
    depends_on:
      - backend

  # Frontend Nginx
  frontend:
    build:
      context: ./frontend
      args:
        - ARG_BACKEND_URL=http://localhost:9000/api
    env_file:
      - ./frontend/.env.prod
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transcriber
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    hostname: transcriber-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@transcriber-rabbit
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf

volumes:
  media_volume:
  postgres_data:
  rabbitmq_data:
  static_volume:
  whisper_models:
