# Generated by Django 4.2.6 on 2023-11-11 15:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231104_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('simple', 'Others')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcription_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='app.project'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=django.contrib.postgres.indexes.GinIndex(fields=['transcription_vector'], name='app_audio_transcr_ae6dc8_gin'),
        ),
        # Add triggers to update columns
        migrations.RunSQL(
            sql='''
                CREATE OR REPLACE FUNCTION update_transcription()
                RETURNS TRIGGER
                AS
                $$
                BEGIN
                    NEW.transcription_vector := to_tsvector(NEW.language::regconfig, NEW.transcription);
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER transcription_vector_trigger
                BEFORE INSERT OR UPDATE OF transcription, language
                ON app_audio
                FOR EACH ROW EXECUTE PROCEDURE update_transcription();

                UPDATE app_audio SET language = language;
            ''',
            reverse_sql = '''
                DROP TRIGGER IF EXISTS transcription_vector_trigger
                ON app_audio;
                DROP FUNCTION IF EXISTS update_transcription;
            '''
        ),
    ]
